/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2021-03-12 01:28:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class scheduleappointment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"beige\">\r\n");
      out.write("<center><h1>Welcome to Patient Portal\r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("<a href = \"patientprofile.jsp\">Patient Profile</a> | <a href = \"scheduleappointment.jsp\">Schedule Appointment</a> |\r\n");
      out.write("<a href = \"patientappointmentview.jsp\">View Appointment</a> | <a href = \"index.html\">Logout</a></h1>\r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("<form action=\"./addappointment.jsp\" method=\"post\">\r\n");
      out.write("<input type=\"text\" name = \"PatName\" placeholder=\"Patient Name\">\r\n");
      out.write("<input type=\"date\" name = \"AppmntDate\" placeholder=\"Date\">\r\n");
      out.write("<input type=\"time\" name = \"AppmntTime\" placeholder=\"Time\">\r\n");
      out.write("<input type=\"text\" name = \"DrName\" placeholder=\"Dr Name\">\r\n");
      out.write("<select name = \"DrSpl\">\r\n");
      out.write("<option value=\"ENT\">ENT</option>\r\n");
      out.write("<option value=\"Cardiologist\">Cardiologist</option>\r\n");
      out.write("<option value=\"Dermatologist\">Dermatologist</option>\r\n");
      out.write("<option value=\"Orthopedic\">Orthopedic</option>\r\n");
      out.write("<option value=\"Ophthalmologist\">Ophthalmologist</option>\r\n");
      out.write("<option value=\"Infection Specialist\">Infection Specialist</option>\r\n");
      out.write("<option value=\"Nutritionist\">Nutritionist</option>\r\n");
      out.write("<option value=\"Pediatrition\">Pediatrition</option>\r\n");
      out.write("<option value=\"Neurologist\">Neurologist</option>\r\n");
      out.write("<option value=\"Psychatrist\">Psychatrist</option>\t\t\r\n");
      out.write("</select>\r\n");
      out.write("<input type=\"hidden\" name = \"Status\" placeholder=\"Pending\">\r\n");
      out.write("<input type=\"submit\" value = \"Schedule\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
